import { CuePattern, ICueCard, PaperCupBooleanParams } from './schema';

export const PARAM_CODES: { [key: string]: string } = {
  hasWoTopic: 'a',
  hasNiTopic: 'b',
  hasNoneTopic: 'c',
  hasWoGrouping: 'd',
  hasNiGrouping: 'e',
  hasNoneGrouping: 'f',
  hasStraightOrder: 'g',
  hasInvertOrder: 'h',
  hasPositive: 'i',
  hasNegative: 'j',
  hasGroupingTopic: 'k',
};

export const INITIAL_PARAMS: PaperCupBooleanParams = {
  hasWoTopic: false,
  hasNiTopic: false,
  hasNoneTopic: false,
  hasWoGrouping: false,
  hasNiGrouping: false,
  hasNoneGrouping: false,
  hasStraightOrder: false,
  hasInvertOrder: false,
  hasPositive: false,
  hasNegative: false,
  hasGroupingTopic: false,
};

export const TARGET = {
  none: 'none',
  wo: 'wo',
  ni: 'ni',
};

export const PAPERCUP_PATTERNS: CuePattern[] = [
  {
    wo: 'を',
    ni: 'に',
    topic: 'none',
    doushi: '入れる',
    sentence: '青を赤に入れる',
    grouping: 'none',
    isWoFirst: true,
    isNegative: false,
  },
  {
    wo: 'を',
    ni: 'に',
    topic: 'none',
    doushi: '入れない',
    sentence: '青を赤に入れない',
    grouping: 'none',
    isWoFirst: true,
    isNegative: true,
  },
  {
    wo: 'を',
    ni: 'に',
    topic: 'none',
    doushi: '入れる',
    sentence: '赤に青を入れる',
    grouping: 'none',
    isWoFirst: false,
    isNegative: false,
  },
  {
    wo: 'を',
    ni: 'に',
    topic: 'none',
    doushi: '入れない',
    sentence: '赤に青を入れない',
    grouping: 'none',
    isWoFirst: false,
    isNegative: true,
  },
  {
    wo: 'は',
    ni: 'に',
    topic: 'none',
    doushi: '入れない',
    sentence: '青は赤に入れない',
    grouping: 'wo',
    isWoFirst: true,
    isNegative: true,
  },
  {
    wo: 'は',
    ni: 'に',
    topic: 'none',
    doushi: '入れない',
    sentence: '赤に青は入れない',
    grouping: 'wo',
    isWoFirst: false,
    isNegative: true,
  },
  {
    wo: 'を',
    ni: 'には',
    topic: 'none',
    doushi: '入れない',
    sentence: '青を赤には入れない',
    grouping: 'ni',
    isWoFirst: true,
    isNegative: true,
  },
  {
    wo: 'を',
    ni: 'には',
    topic: 'none',
    doushi: '入れない',
    sentence: '赤には青を入れない',
    grouping: 'ni',
    isWoFirst: false,
    isNegative: true,
  },
  {
    wo: 'は',
    ni: 'に',
    topic: 'wo',
    doushi: '入れる',
    sentence: '青は赤に入れる',
    grouping: 'none',
    isWoFirst: true,
    isNegative: false,
  },
  {
    wo: 'は',
    ni: 'に',
    topic: 'wo',
    doushi: '入れない',
    sentence: '青は赤に入れない',
    grouping: 'none',
    isWoFirst: true,
    isNegative: true,
  },
  {
    wo: 'は、',
    ni: 'に',
    topic: 'wo',
    doushi: '入れない',
    sentence: '青は、赤に入れない',
    grouping: 'wo',
    isWoFirst: true,
    isNegative: true,
  },
  {
    wo: 'は',
    ni: 'には',
    topic: 'wo',
    doushi: '入れない',
    sentence: '青は赤には入れない',
    grouping: 'ni',
    isWoFirst: true,
    isNegative: true,
  },
  {
    wo: 'を',
    ni: 'には',
    topic: 'ni',
    doushi: '入れる',
    sentence: '青には赤を入れる',
    grouping: 'none',
    isWoFirst: false,
    isNegative: false,
  },
  {
    wo: 'を',
    ni: 'には',
    topic: 'ni',
    doushi: '入れない',
    sentence: '青には赤を入れない',
    grouping: 'none',
    isWoFirst: false,
    isNegative: true,
  },
  {
    wo: 'は',
    ni: 'には',
    topic: 'ni',
    doushi: '入れない',
    sentence: '青には赤は入れない',
    grouping: 'wo',
    isWoFirst: false,
    isNegative: true,
  },
  {
    wo: 'を',
    ni: 'には、',
    topic: 'ni',
    doushi: '入れない',
    sentence: '青には、赤を入れない',
    grouping: 'ni',
    isWoFirst: false,
    isNegative: true,
  },
];

export const CUE_CARDS: {
  [key: string]: {
    id: string;
    hasTailAccent: boolean;
  } & ICueCard;
} = {
  red: {
    id: 'red',
    label: '赤',
    pitchStr: 'あ＼か',
    hasTailAccent: false,
  },
  blue: {
    id: 'blue',
    label: '青',
    pitchStr: 'あ＼お',
    hasTailAccent: false,
  },
  green: {
    id: 'green',
    label: '緑',
    pitchStr: 'み＼どり',
    hasTailAccent: false,
  },
  yellow: {
    id: 'yellow',
    label: '黄色',
    pitchStr: 'きいろ',
    hasTailAccent: false,
  },
  ireru: {
    id: 'ireru',
    label: '入れる',
    pitchStr: 'いれる',
    hasTailAccent: false,
  },
};

export const PITCH_STRS: { [key: string]: string } = {
  赤: 'あ＼か',
  青: 'あ＼お',
  黄色: 'きーろ',
  緑: 'み＼どり',
  を: 'を',
  に: 'に',
  は: 'は',
  には: 'に＼は',
};
